# Generated by Django 5.2.8 on 2025-11-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='report/'),
        ),
    ]
