# Generated by Django 5.2.8 on 2025-11-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='accident_videos/'),
        ),
    ]
