# Generated by Django 5.2.8 on 2025-11-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0004_accidentreport_mobile_accidentreport_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
